### ISSUE TITLE
INFOGRAFIA 

### ISSUE THREAD

**Issue by saul19bautista** [SistemasTecTlaxiaco/actividad-1-infografia-saul19bautista-1#1]
[INFOGRAFIA SOFTWARE.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-saul19bautista-1/files/14274530/INFOGRAFIA.SOFTWARE.pdf)

**Comment by Elisahadad** [comment]
19 / 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
